service: mic-db

frameworkVersion: '3'

plugins:
    - serverless-sequelize-migrations

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
            - 's3:DeleteObjectVersion'
          Resource: 
            - "arn:aws:s3:::*"
  environment:
    prefixApp: MIC-DB
    STAGE: ${self:provider.stage}
    DB_DIALECT: 'mysql'
    DB_NAME: 'database_name'
    DB_USERNAME: 'database_username'
    DB_PASSWORD: 'database_password'
    DB_HOST: 'database_host'
    DB_PORT: 'database_port'
  

    